language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
  - cp .env.example .env
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - python manage.py test